site_name: Liliklu
site_description: 'A docs test'
site_author: 'Ute Klinke'
site_url: https://liliklu.de
docs_dir: docs/
repo_name: 'mhausenblas/mkdocs-template'
repo_url: 'https://github.com/mhausenblas/mkdocs-template'
# nav:
#     - Home: index.md
theme:
  name: 'material'
