site_name: Liliklu
site_description: ''
site_author: 'Ute Klinke'
site_url: https://liliklu.de
docs_dir: docs/
plugins:
  - awesome-pages
theme:
  name: mkdocs
  custom_dir: overrides/
  locale: de
  navigation_depth: 3
  analytics:
      gtag: UA-217783440-1

extra_css:
    - css/extra.css

#theme:
#  name: null
#  custom_dir: 'custom_theme/'

